// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUM_FBPROTOCOL_H_
#define FLATBUFFERS_GENERATED_ENUM_FBPROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 7,
             "Non-compatible flatbuffers version included");

namespace FBProtocol {

enum OBJECTTYPE : int8_t {
  OBJECTTYPE_NONE = 0,
  OBJECTTYPE_PlayerInfo = 1,
  OBJECTTYPE_OBJECT = 2,
  OBJECTTYPE_GAMEOBJECT = 3,
  OBJECTTYPE_MIN = OBJECTTYPE_NONE,
  OBJECTTYPE_MAX = OBJECTTYPE_GAMEOBJECT
};

inline const OBJECTTYPE (&EnumValuesOBJECTTYPE())[4] {
  static const OBJECTTYPE values[] = {
    OBJECTTYPE_NONE,
    OBJECTTYPE_PlayerInfo,
    OBJECTTYPE_OBJECT,
    OBJECTTYPE_GAMEOBJECT
  };
  return values;
}

inline const char * const *EnumNamesOBJECTTYPE() {
  static const char * const names[5] = {
    "NONE",
    "PlayerInfo",
    "OBJECT",
    "GAMEOBJECT",
    nullptr
  };
  return names;
}

inline const char *EnumNameOBJECTTYPE(OBJECTTYPE e) {
  if (::flatbuffers::IsOutRange(e, OBJECTTYPE_NONE, OBJECTTYPE_GAMEOBJECT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOBJECTTYPE()[index];
}

}  // namespace FBProtocol

#endif  // FLATBUFFERS_GENERATED_ENUM_FBPROTOCOL_H_
